FROM php:${php.version}-cli-${php.variant}

# Magento 2 does not support Composer 2
COPY --from=composer:1 /usr/bin/composer /usr/bin/composer

<% if (php.variant.startsWith('alpine')) { %>
    RUN apk add --no-cache unzip \
        rsync \
        freetype-dev \
        libjpeg-turbo-dev \
        libpng-dev \
        icu-dev \
        libxslt-dev \
        libzip-dev \
        curl \
        g++ \
        make \
        libxml2-dev \
        git \
        libsodium-dev
<% } else { %>
    RUN echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list

    RUN apt-get update && apt-get -t stretch-backports install -y \
        unzip \
        rsync \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libicu-dev \
        libxslt-dev \
        libzip-dev \
        curl \
        build-essential \
        libxml2-dev \
        git-core \
        libsodium-dev
<% } %>

# See https://github.com/docker-library/php/issues/912#issuecomment-559918036
<% if (semver.satisfies(semver.coerce(php.version), '>= 7.4')) { %>
    RUN docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ && docker-php-ext-install gd
<% } else { %>
    RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && docker-php-ext-install gd
<% } %>

RUN docker-php-ext-install intl
RUN docker-php-ext-install xsl
RUN docker-php-ext-install zip
RUN docker-php-ext-install pdo pdo_mysql
RUN docker-php-ext-install soap
RUN docker-php-ext-install bcmath
RUN docker-php-ext-install sodium

# "sockets" is only necessary for Magento >= 2.4
<% if (semver.satisfies(semver.coerce(magento), '>= 2.4')) { %>
    RUN docker-php-ext-install sockets
<% } %>