FROM php:${php.version}-cli-${php.variant}

# Magento 2 does not support Composer 2
COPY --from=composer:1 /usr/bin/composer /usr/bin/composer

<% if (semver.satisfies(semver.coerce(php.version), '>= 7.4')) { %>
    RUN echo "Hello, World"
<% } else { %>
    RUN echo "Foo, Bar"
<% } %>